# docker compose exec php sh
services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/opt/project
    command: ['composer', 'install']
#    command: ['tail', '-f', '/dev/null']
